### ISSUE TITLE
Whatsapp.post() results in 401 error

### ISSUE THREAD

**Issue by arivanbastos** [Secreto31126/whatsapp-api-js#114]
First, thank you for the good and very promising library.

**Issue details**
- Calling Whatsapp.post() always results in 401 error.
- secret and token are checked.
- Webhook URL register was previouly successfuly done.
- Previous 0.8 version was working fine.
- JSON string (message data) sent by Meta/Whatsapp servers in post body seems ok (it is correctly displayed in console.log).
- Library version: 1.0.0-beta.5
- Node 18.15.0

**app.js**
```
import { createServer } from "http";
import crypto from "crypto";';
import { fetch } from "undici";
...

const Whatsapp = new WhatsAppAPI({ 
    token: MY_TOKEN, 
    appSecret: MY_APP_SECRET, 
    ponyfill: {
        fetch, 
        subtle: crypto.subtle
    }
});

const requestListener = function (req, res) {
  if (req.method == "POST") {
          let body = [];
          req.on('data', (chunk) => {
              body.push(chunk);
          }).on('end', () => {
              var bodyStr = Buffer.concat(body).toString();
              console.log(bodyStr);
              //Handlers.post(JSON.parse(bodyStr), onMessage);
              Whatsapp.post(JSON.parse(bodyStr), bodyStr, req.headers["X-Hub-Signature-256"]).then(()=>{
                  res.end(JSON.stringify({url: req.url, error: 0}));
              }).catch((err) => {
                   // Always catchs here (err = 401).
                   console.error(err);
               });
          });
   }
};

Whatsapp.on.message = async ({ phoneID, from, message, name, raw }) => {
   console.log(`User ${name} (${from}) sent to bot ${phoneID} ${JSON.stringify(message)}`);
};

const server = createServer(requestListener);
server.listen(80, () => {
    console.log(`Server is running`);
});
```

**package.json**
```
{
  "type": "module",
  "dependencies": {
    "crypto": "^1.0.1",
    "dotenv": "^16.0.3",
    "query-string": "^8.1.0",
    "undici": "^5.21.0",
    "whatsapp-api-js": "^1.0.0-beta.5"
  }
}
```

**Additional Suggestions**
I got difficulties to setup the new library version (1.0.0) compared to the previous version.

- First, the @latest version doest not corresponds to github readme file, which made me a  little confuse. This resulted in "Cannot find module 'whatsapp-api-js/messages'" and another errors. 
- After install the 1.0.0 beta version I got "crypto undefined" error when running my app. I had to look at the lib code to realize that it is necessary to provide a **ponyfill object (?) with "fetch" and "subtle" attributes (?)**. I had difficulties to understand and setup these parameters,  so please consider provide a more detailed documentation about how setup these parameters (maybe a full setup example using common libraries).

**Comment by Secreto31126** [comment]
I'm 99% sure the issue is coming from the new header check added a few pulls ago.

I actually never got myself into testing it (I know, a genius move from my side). The official documentation doesn't explain a lot about the verification process, so it's been a guessing game since the beginning.

Anyway, just to be sure it's not the 1%, does  `req.headers["X-Hub-Signature-256"]` start with `"sha256="`? If it does, then the issue is definitely at the verification process and it should be revised (future me note: add it to the roadmap and test it in a few weeks when I'm back on my notebook)

I never got convinced by the check feature because of the lack of documentation, hence the option to toggle it off. On the main constructor, simply add { secure: false } to the object and the library will work almost as it used to do in v0 (of course it's just a workaround and not ideal, but it's the best I can do right now)

---

About the first point, I pushed a few hours ago an update to include the version of the code in the readme title. However you are right in saying it should be clearer, I will fix that ASAP.

On the other hand, I'm actually surprised you needed to configure the ponyfills for crypto and fetch. IIRC, fetch should be available globally since Node 17, and crypto.subtle had been around for even longer, so they shouldn't be needed in Node 18. Would you mind opening a new issue so we can tackle that problem separately? A tracelog for the "crypto is undefined" error would be really cool :)

Btw, I'm planning to add a changelog to help with the v1 transition, and also lots of tutorials for a full set up (they would even help me too, Facebook is terrible at explaining how to get a permanent token and I always forget how I did it the first time), although I had to delay both of them as my life had become a little nightmare in the last 6 weeks, just at the same time the library became popular 🙃

I hope I can get to help you with the problems soon, thanks for opening the issue!

P.D.: I wrote way too many parentheses 😁

**Comment by Secreto31126** [comment]
> Anyway, just to be sure it's not the 1%, [...]

Sometimes My Genius... Is Almost Frightening...

It was the 1% all along... The right header is `x-hub-signature-256`, all lowercase. Turns out it was a day 0 bug since #55 when the code was first implemented and spreaded into the documentation. It only took me a month to write a new testing code and find the issue 😄.

The simplest solution will be writting Middlewares as discused [here](https://github.com/Secreto31126/whatsapp-api-js/pull/57#issuecomment-1426996702), or something along the lines of the new enviroment setups.

I will definitely add more example codes to make sure this bug doesn't happen again. I will make sure to include your snippet :)

Thanks for opening the issue!
