### ISSUE TITLE
Lib doesn't work with typescript

### ISSUE THREAD

**Issue by arivanbastos** [Secreto31126/whatsapp-api-js#157]
**Describe the bug**
Compiling errors in a clean typescript project.

**To Reproduce**
1. Setup the project
npm init -y
npm install typescript --save-dev
npm install @types/node --save-dev
npx tsc --init --rootDir src --outDir build --esModuleInterop --resolveJsonModule --lib es6 --module commonjs --allowJs true --noImplicitAny true
mkdir src   
mkdir build
npm install whatsapp-api-js

2. Create src/index.ts file
```
import WhatsAppAPI from "whatsapp-api-js";
import { Text, Image, Document } from "whatsapp-api-js/messages";

var whatsapp = new WhatsAppAPI({ 
    token: 'a', 
    appSecret: 'b' 
});
```

3. Compile
npx tsc

**Expected behavior**
The project is compiled sucessfully.

**Current behavior**
```
error TS2307: Cannot find module 'whatsapp-api-js/messages' or its corresponding type declarations.
3 import { Text, Image, Document } from "whatsapp-api-js/messages";

src/index.ts:5:20 - error TS2351: This expression is not constructable.
  Type 'typeof import("./path/to/project/node_modules/whatsapp-api-js/types/index")' has no construct signatures.
5 var whatsapp = new WhatsAppAPI({
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Runtime node@18.15.0
 - Library Version 0.8.2

**Additional context**
1. Got the same problem with whatsapp-api-js@beta version.
2. tsconfig.js
```
{
  "compilerOptions": {
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "lib": ["es6"],                                      /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "module": "commonjs",                                /* Specify what module code is generated. */
    "rootDir": "src",                                    /* Specify the root folder within your source files. */
    "resolveJsonModule": true,                           /* Enable importing .json files. */
    "allowJs": true,                                     /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
    "outDir": "build",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "noImplicitAny": true,                               /* Enable error reporting for expressions and declarations with an implied 'any' type. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```

**Comment by Secreto31126** [comment]
I definitely failed to remark the differences in the transition from v0 to v1. The import syntax you mentioned is all v1.

## v0

In order to use v0, you must require the package the following way:

```js
const { WhatsAppAPI, Types } = require("whatsapp-api-js");
const { Text, Media, Contacts } = Types;
```

And, in order to use it with ESM (TypeScript imports, if I'm not wrong, should auto fix this, but idk):

```js
import WhatsAppPKG from "whatsapp-api-js";
const { WhatsAppAPI, Types } = WhatsAppPKG;
const { Text, Media, Contacts } = Types;
```

[v0 documentation.](https://secreto31126.github.io/whatsapp-api-js/0.8.2/)

I know, ugly. That's why I tried to fix it in v1.

## v1

On the one hand, there's a known issue with the main import, which I'm struggling a lot to fix. However, there's a temporal fix for it:

```ts
import WhatsAppAPI from "whatsapp-api-js/index";
```

It's among the issues that prevent me from releasing v1. If I'm unable to fix it soon, I will consider it not a bug, but a feature 😄.

On the other hand, I failed to replicate your issue with the messages import. It's working on my side.

[StackBlitz because I don't have my notebook rn](https://stackblitz.com/edit/github-dkynmk?file=tsconfig.json,package.json,api%2Findex.ts)

I'm sorry for all the mess in the transition, I failed to keep v0 usable while developing v1. I'm just hoping it will all be forgotten after the new version release :)

**Comment by arivanbastos** [comment]
It worked using v1 lib and the following code:
```
import WhatsAppAPI from "whatsapp-api-js/index";
import { Text, Image, Document } from "whatsapp-api-js/messages";
```

Additionally i needed import GetParams type to make get method works:
import { GetParams } from "whatsapp-api-js/types";
...
let params: GetParams = {
    'hub.mode': 'subscribe',
    'hub.verify_token': {my verify token},
    'hub.challenge': {my challenge},
};
whatsapp.get(params);

Thank u.

**Comment by Secreto31126** [comment]
Hi! I just released beta.8 to npm, which should fix the main import issue.

If you don't mind, please let me know if you can now import it without the /index trick. If it does, I will publish it as a stable release this weekend.

Thanks 😁

**Comment by arivanbastos** [comment]
Hi! It works!

Thank u
