### ISSUE TITLE
Cannot set button index during construction, resulting unable to send call button + url button at the same template.

### ISSUE THREAD

**Issue by TomerAvni** [Secreto31126/whatsapp-api-js#175]
**Describe the bug**
Having a template with 2 action buttons (order is important):
1. Call
2. Dynamic Url

**To Reproduce**
1. Create a template having 2 buttons, the first one 'call phone number' and the second 'visit website' - dynamic.
2. Create the template using the whatsapp-api-js (current package), **Generating only the dynamic visit website button component**
3. Send.
4. Throws index is incorrect.

**Expected behavior**
Unable manually setting the button index.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Runtime [e.g. node@16]
 - Library Version [e.g. 1.0.2]

**Additional context**
Consider the following:

```
const dynamicButtons = templatePart.buttons.reduce((buttons, templateButton, idx) => {
      if (templateButton.type === TEMPLATE_BUTTON_TYPE.URL) {
          return [...buttons, new ButtonComponent('url', templateValues.pop())];
      }

      return buttons;
 }, []);

const body =...;

new Template('waName', 'language', body, ...dynamicButtons)
```

This will insert sole the url param and not the call phone number param, which results a facebook error.
If the order is reversed (url, phonenumber) then all is good, however that is not necessarily the expected behavior. 

Thanks.

**Comment by Secreto31126** [comment]
Hi!

[As stated in the documentation](https://secreto31126.github.io/whatsapp-api-js/1.0.2/classes/messages.ButtonComponent.html), the index of the buttons is selected by the order of the inserted parameters.

This design simplifies the template variables a lot, as it black boxes the index management to the end user so it doesn't have to keep track of it to prevent duplicates or missing IDs. However, as you mentioned, it sometimes makes automation a little harder.

Unfortunately, at the current implementation of the code it seems to be hard to fix the issue, as the parameters received by the constructor are strings rather than a class, so it won't be easy to send a custom index argument.

I will reread the issue in a week, as right now I'm not available.

**Comment by Secreto31126** [comment]
PS: I'm a little confused by your code example, as a Template should only have one ButtonComponent with a type and one to three string variables as the buttons parameters.

Example from [EXAMPLES/template.md](https://github.com/Secreto31126/whatsapp-api-js/blob/main/EXAMPLES/template.md#complex-template-with-call-to-action-url)

```ts
new Template(
    "template_name",
    new Language("en"),
    new ButtonComponent(
        "url",
        "?user_id=123",
        "?user_id=123&product_id=456"
    )
);
```

**Comment by Secreto31126** [comment]
After further searching in the docs, I have come to the conclusion that there's a "mistake" in the library.

Seems like WhatsApp's template creator no longer accepts multiple links in their call to action buttons, so the code example I sent earlier doesn't apply to reality. On the other hand, phone numbers can't take variables, so the only parameter you should be setting up in the Template constructor should be the one for the dynamic url.

However, you mentioned that changing the order of the buttons does work, which is weird because the template creator still marks the dynamic url variable as the variable 1:

![image](https://github.com/Secreto31126/whatsapp-api-js/assets/46955459/9d552373-82af-4f41-9b65-555cebb5b1c3)
(Sorry for the image in spanish, I don't know how to translate Meta Developers' website to english)

As mentioned earlier, I will do a proof test of the API on Friday.

Thanks for opening the issue!

**Comment by TomerAvni** [comment]
Thank you.
Indeed the issue is pretty simple (and not extremely important):
There is no way (without forcing the template post generation) to send the image you attached.
I’d also expect the API (that is Meta CloudAPI) to handle it gracefully since they only accept dynamic action buttons when using a template, (so why forcing the index if it’s self decided?!).

Thanks!

**Comment by Secreto31126** [comment]
Almost 48 hours later I finally got authorized to use a template with the structure mentioned earlier this week (phone, url). Upon testing it with the following snippet:

```typescript
new Template(
    "buttons",
    "en",
    new ButtonComponent(
        "url",
        "example"
    )
);
```

I got greeted with this error:

```json
{
  error: {
    message: '(#100) Invalid parameter',
    type: 'OAuthException',
    code: 100,
    error_data: {
      messaging_product: 'whatsapp',
      details: 'buttons: **Button at index 0 is of type Call and does not support parameters**'
    },
    fbtrace_id: 'AWGTuZQ24d-gWqU95Law9sE'
  }
}
```

As you said, the API effectively expects you to skip the phone number, even though it doesn't have a parameter!

This might be the dumbest choice design from the API team. I already thought the message's structure was terrible (specially for JS objects), but expecting the user to not use a variable even though there's NO variable... It breaks me...

My best solution for the issue would be adding a _"dummy"_ object (`undefined` or `false`), which will be ignored when the buttons are constructed, hence skipping the phone "variable" index.

I'm just glad this is an easy fix for a dumb problem. I will add the feature and in an hour or two will publish 1.0.3 to npm.

Thanks for reporting the bug!
