### ISSUE TITLE
Downgrade to node 16.

### ISSUE THREAD

**Issue by TomerAvni** [Secreto31126/whatsapp-api-js#271]
**Is your feature request related to a problem? Please describe.**
I am using node v16 with 2.1 (although it supposedly not supported).
Since not using typescript (using commonjs) I can't upgrade so can't use flows and others.
Is 18 really mandatory??
Thanks.

**Comment by Secreto31126** [comment]
Just to make sure, your issue is not being able to download the latest versions using npm because package.json sets engine to >=18, right?

If so, I can lower the requirement. However, I won't test the library against those versions, so breaking issues may happen.

**Comment by TomerAvni** [comment]
Hi, thanks for your reply!
No,
I am using node 16.x with commonjs and up to 2.1 it works great, tried many components.
From 2.2 on, when installing a higher version, it doesn't let me init any of the component classes:
As an example:
`new Text('some-text')`
throws
`TypeError: Text is not a constructor`

It does not happen on 2.1

Thanks.

**Comment by Secreto31126** [comment]
I spent some time testing the library in Runkit with CJS, and I think I found the issue:

When using the require(".../messages") command, most of the classes do get required as expected, however, there are 3 classes that are default exported (Text, Reaction and Location). Simply requiring them won't work because they are under the default property.

Here's an example code to make it clear:

```js
const { Image, Interactive, Text, Reaction } = require("whatsapp-api-js/messages");

const normal_export1 = new Image("url");
const normal_export2 = new Interactive(...);

const default_export1 = new Text.default("Hi");
const default_export2 = new Reaction.default("Hi");
```

I have an idea on how to fix this issue from the library side. I will do a release in an hour at most, so let me know if it works.

---

PS: May I ask what's your use case for Node 16 and CJS? I had been struggling maintaining support to requiring the library, and I thought about dropping it for the sake of simplicity. However, seeing there's still people using CJS, I might keep it a little longer, and I would love to know your reasons!

**Comment by TomerAvni** [comment]
Wow man,
What a fast reply!
I really appreciate this!
Well, I am using since 16.x since I am simply using it.
It’s a relatively large project of mine (having 1000+ unit tests) and migrating to a newer node breaks many things which I simply can’t afford modifying…
I’d suspect this is the usual suspect of any complex upgrade.

THX!

**Comment by Secreto31126** [comment]
Over a thousand unit tests!? That's a lot, I barely got to write 74 unit tests for this library 🤣

I just pushed the changes to #272, I will wait for the tests and make a beta release before going public.

**Comment by TomerAvni** [comment]
Yap, many lines of code!
B.T.W, if I may,
Why did you separate  ActionCTA and Button ?
When creating Interactive, it makes them hard to be polymorphic to each other and if using on over the other, the API is significantly different.
I think another approach would be to handle them the same, which should make it easier to interact with.

const interactive = new Interactive(
    …[ActionCTA | Button],
    new Body("You should google it")
);

Regardless, Thanks for your help.
It’s really appreciated.
Tomer.

**Comment by Secreto31126** [comment]
Sorry, I didn't follow, what's the issue with ActionCTA and Button? They don't correlate at all, specially Button which is a parameter for [ActionButtons](https://whatsappapijs.web.app/classes/messages.ActionButtons.html) rather than an Interactive parameter.

All actions are under the interface [InteractiveAction](https://whatsappapijs.web.app/interfaces/types.InteractiveAction.html), so ActionCTA and ActionButtons implements it. IIRC, you can have up to 3 reply buttons, compared to only 1 CTA url. Also, none of them share internal properties, so I don't know how you would make them more similar to each other.

In older versions it used to be the same class for ActionButtons and ActionList, only changing a string to set the type. However, I had to split the classes with the release of even more actions, such as Products, Flows and CTA.

I know it makes the code less neat in some cases, but it improves a lot the typing and the documentation.

Here's an example code of how to use them (in TS to highlight the types):

```ts
import { Interactive, Body, ActionCTA, ActionButtons, Button } from "whatsapp-api-js/messages";
import type { InteractiveAction } from "whatsapp-api-js/types";

const message_type: "cta" | "buttons" = "cta"; // User input

let action: InteractiveAction;
if (message_type === "cta") action = new ActionCTA("Open Google", "https://google.com");
else action = new ActionButtons(new Button("id", "Reply message"));

const message = new Interactive(
    action,
    new Body("Hi ✋")
);
```

**Comment by TomerAvni** [comment]
You’re right.
My bad.

Thanks again!

**Comment by Secreto31126** [comment]
No problem, happy to help.

I just released the fix to beta, you can install it using:

```sh
npm install whatsapp-api-js@beta
```

Let me know if it fixes the issues!
